language: r
sudo: false
r: devel
cache: packages

latex: true


script:
  - |
    travis_wait 42 R CMD build .
    travis_wait 59 R CMD check ttBulk*tar.gz

after_script:
  - tar -ztvf ttBulk_*.tar.gz
  - echo ${NOT_CRAN}

after_success:
  - travis_wait 40 tar -C .. -xf $PKG_TARBALL

after_failure:
- cat ttBulk.Rcheck/00*
